"""add is_processing to reminders

Revision ID: 2e30b77b5f0d
Revises: 51f271016cfa
Create Date: 2026-05-12 13:03:31.646032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e30b77b5f0d'
down_revision: Union[str, Sequence[str], None] = '51f271016cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_reminders', sa.Column('is_processing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_reminders', 'is_processing')
    # ### end Alembic commands ###
