"""add notification model

Revision ID: 87dd6dfc91c7
Revises: ec6842f32aab
Create Date: 2026-05-27 14:31:32.548140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87dd6dfc91c7'
down_revision: Union[str, Sequence[str], None] = 'ec6842f32aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_reminders', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('application_reminders', sa.Column('last_retry_at', sa.DateTime(), nullable=True))
    op.add_column('application_reminders', sa.Column('failed_at', sa.DateTime(), nullable=True))
    op.add_column('application_status_history', sa.Column('old_status', sa.Enum('APPLIED', 'INTERVIEWING', 'OFFER', 'ACCEPTED', 'REJECTED', 'GHOSTED', name='applicationstatus'), nullable=True))
    op.add_column('application_status_history', sa.Column('new_status', sa.Enum('APPLIED', 'INTERVIEWING', 'OFFER', 'ACCEPTED', 'REJECTED', 'GHOSTED', name='applicationstatus'), nullable=False))
    op.drop_column('application_status_history', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status_history', sa.Column('status', postgresql.ENUM('APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', name='applicationstatus'), autoincrement=False, nullable=False))
    op.drop_column('application_status_history', 'new_status')
    op.drop_column('application_status_history', 'old_status')
    op.drop_column('application_reminders', 'failed_at')
    op.drop_column('application_reminders', 'last_retry_at')
    op.drop_column('application_reminders', 'retry_count')
    # ### end Alembic commands ###
