"""add user role

Revision ID: 9bcd70e79212
Revises: 87dd6dfc91c7
Create Date: 2026-06-01 08:24:14.505551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bcd70e79212'
down_revision: Union[str, Sequence[str], None] = '87dd6dfc91c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('application_reminders', 'failed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    user_role = postgresql.ENUM(
        'USER',
        'ADMIN',
        name='userrole'
    )
    user_role.create(op.get_bind())

    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('applications', 'deleted_at')
    op.alter_column('application_reminders', 'failed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
