"""add processing_started_at

Revision ID: ec6842f32aab
Revises: 2e30b77b5f0d
Create Date: 2026-05-18 12:48:45.981375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6842f32aab'
down_revision: Union[str, Sequence[str], None] = '2e30b77b5f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_reminders', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_reminders', 'processing_started_at')
    # ### end Alembic commands ###
